services:
  kafka:
    build: ./kafka
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  web:
    build: ./web
    container_name: web_flask
    ports:
      - "5050:5050"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:9092"
    volumes:
      - wordclouds_vol : app/prepared_wordclouds

  worker:
    build: ./worker
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:9092"
    volumes:
      - wordclouds_vol : app/prepared_wordclouds
    deploy:
      replicas: 1
  
  volumes:
  - wordclouds_vol